---
- ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    openjdk_app: jre
- name: Looking for install in {{ wildfly_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ wildfly_install_dir }}'
  changed_when: false
  register: wildfly_binary

- when: not wildfly_binary.stat.exists
  block:
    - name: Downloading {{ wildfly_tgz_url }} to {{ wildfly_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ wildfly_tgz_url }}'
        dest: '{{ wildfly_tmp_tgz }}'
        checksum: '{{ wildfly_checksum }}'
        mode: '644'

    - name: Unarchiving {{ wildfly_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ wildfly_tmp_tgz }}'
        dest: '{{ wildfly_install_parent_dir }}'
        creates: '{{ wildfly_install_dir }}'
  always:
    - name: Rm {{ wildfly_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ wildfly_tmp_tgz }}'
        state: absent

- name: Linking {{ wildfly_link_dir }} to {{ wildfly_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ wildfly_install_dir }}'
    dest: '{{ wildfly_link_dir }}'
    state: link

- name: Adding wildfly to the default path
  become: true
  become_user: root
  with_items:
    - f: wildfly.sh
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("644") }}'
